# Generated by Django 4.1.1 on 2023-04-19 05:07

import django.contrib.auth.validators
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial_squashed"),
        ("peddleconcept", "0002_deputy_models_upgrade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PeddleRider",
        ),
        migrations.DeleteModel(
            name="PeddleWebUser",
        ),
        migrations.AlterModelOptions(
            name="peddleuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="abn",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="bank_acct",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="bank_bsb",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="is_rider",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="login_token",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="rider_pay_rate",
        ),
        migrations.RemoveField(
            model_name="peddleuser",
            name="rider_priority",
        ),
        migrations.AlterField(
            model_name="peddleuser",
            name="password",
            field=models.CharField(
                default=make_password(None),
                max_length=128,
                verbose_name="password",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="peddleuser",
            name="username",
            field=models.CharField(
                default="nouser",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
