# Generated by Django 4.1.1 on 2023-04-08 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RowSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("desc", models.TextField(blank=True, verbose_name="Description")),
                ("rowset_type", models.CharField(max_length=100)),
                ("change_index", models.PositiveIntegerField(default=0)),
                (
                    "when_data_changed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "when_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("changes", models.JSONField(default=dict)),
                ("lock_time", models.DateTimeField(blank=True, null=True)),
                (
                    "lock_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rowset (Do Not Edit)",
                "verbose_name_plural": "Rowsets (Do Not Edit)",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name_plural": "settings",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_type", models.CharField(blank=True, max_length=200)),
                ("time_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("time_end", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "rowset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="peddleconcept.rowset",
                    ),
                ),
                ("source_row_id", models.CharField(blank=True, max_length=300)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rezdy", "rezdy"),
                            ("fringe", "fringe"),
                            ("", ""),
                            ("auto", "auto"),
                            ("generate_sessions", "generate_sessions"),
                            ("generate_pay_report", "generate_pay_report"),
                            ("user", "user"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.TextField(blank=True)),
                (
                    "source_row_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "live"),
                            ("deleted", "deleted"),
                            ("none", "none"),
                        ],
                        default="live",
                        max_length=50,
                    ),
                ),
                ("field_auto_values", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("drink_special", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of bar contact (if known)",
                        max_length=100,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number (if known)",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_type", models.CharField(blank=True, max_length=500)),
                ("quantity", models.TextField(blank=True)),
                ("tour_date", models.DateField(default=datetime.date.today)),
                ("time_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("time_end", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("pickup_location", models.TextField(blank=True)),
                ("source_row_id", models.CharField(blank=True, max_length=300)),
                (
                    "rowset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tours",
                        to="peddleconcept.rowset",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tours",
                        to="peddleconcept.session",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rezdy", "rezdy"),
                            ("fringe", "fringe"),
                            ("", ""),
                            ("auto", "auto"),
                            ("generate_sessions", "generate_sessions"),
                            ("generate_pay_report", "generate_pay_report"),
                            ("user", "user"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bikes", models.JSONField(blank=True, default=dict)),
                ("customer_contact", models.TextField(blank=True)),
                ("customer_name", models.TextField(blank=True)),
                ("pax", models.PositiveIntegerField(default=0)),
                (
                    "source_row_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "live"),
                            ("deleted", "deleted"),
                            ("none", "none"),
                        ],
                        default="live",
                        max_length=50,
                    ),
                ),
                ("field_auto_values", models.JSONField(blank=True, default=dict)),
                (
                    "show_venues",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Show venue summary if venues are defined",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourRider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rider_role", models.CharField(blank=True, max_length=100)),
                (
                    "rowset",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_riders",
                        to="peddleconcept.rowset",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to="peddleconcept.tour",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to="peddleconcept.session",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rezdy", "rezdy"),
                            ("fringe", "fringe"),
                            ("", ""),
                            ("auto", "auto"),
                            ("generate_sessions", "generate_sessions"),
                            ("generate_pay_report", "generate_pay_report"),
                            ("user", "user"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_row_id", models.CharField(blank=True, max_length=300)),
                (
                    "source_row_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "live"),
                            ("deleted", "deleted"),
                            ("none", "none"),
                        ],
                        default="live",
                        max_length=50,
                    ),
                ),
                ("field_auto_values", models.JSONField(blank=True, default=dict)),
                (
                    "rider",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_arrive", models.DateTimeField()),
                ("time_depart", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "rowset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_venues",
                        to="peddleconcept.rowset",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="peddleconcept.tour",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tours",
                        to="peddleconcept.venue",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="peddleconcept.session",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rezdy", "rezdy"),
                            ("fringe", "fringe"),
                            ("", ""),
                            ("auto", "auto"),
                            ("generate_sessions", "generate_sessions"),
                            ("generate_pay_report", "generate_pay_report"),
                            ("user", "user"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_row_id", models.CharField(blank=True, max_length=300)),
                (
                    "source_row_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "live"),
                            ("deleted", "deleted"),
                            ("none", "none"),
                        ],
                        default="live",
                        max_length=50,
                    ),
                ),
                ("field_auto_values", models.JSONField(blank=True, default=dict)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("venue", "venue"),
                            ("transit", "transit"),
                            ("activity", "activity"),
                        ],
                        default="venue",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiderPaySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_row_id", models.CharField(blank=True, max_length=300)),
                (
                    "source_row_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "live"),
                            ("deleted", "deleted"),
                            ("none", "none"),
                        ],
                        default="live",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rezdy", "rezdy"),
                            ("fringe", "fringe"),
                            ("", ""),
                            ("auto", "auto"),
                            ("generate_sessions", "generate_sessions"),
                            ("generate_pay_report", "generate_pay_report"),
                            ("user", "user"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("tour", "tour"),
                            ("break", "break"),
                            ("manual", "manual"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("pay_rate", models.PositiveIntegerField(default=30)),
                ("pay_reason", models.CharField(blank=True, max_length=200)),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                (
                    "rowset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peddleconcept.rowset",
                    ),
                ),
                (
                    "tour_rider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peddleconcept.tourrider",
                    ),
                ),
                ("pay_minutes", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("field_auto_values", models.JSONField(blank=True, default=dict)),
                (
                    "rider",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
